source = ~/.config/hypr/colors.conf

# BACKGROUND
background {
    monitor =
    color = $primary
    path = $image
    blur_size = 4
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# INPUT FIELD
input-field {
    monitor =
    size = 190, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = false
    font_family = CaskaydiaCove Nerd Font
    placeholder_text = <i><span> Password... </span></i>
    hide_input = false
    position = 0, -170
    halign = center
    valign = center
    outer_color = $outline
    inner_color = $surface_variant
    font_color = $on_surface_variant
    check_color = $primary
    fail_color = $error
    fail_text = <i>Incorrect Password! <b>($ATTEMPTS)</b></i>
}

# Hour-Time
label {
    monitor =
    text = cmd[update:3600000] date +"%I"
    color = $primary
    shadow_passes = 3
    shadow_size = 2
    font_size = 100
    font_family = CaskaydiaCove Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

# Minute-Time
label {
    monitor =
    text = cmd[update:60000] date +"%M"
    color = $primary
    font_size = 100
    font_family = CaskaydiaCove Nerd Font
    shadow_passes = 3
    shadow_size = 2
    position = 0, -20
    halign = center
    valign = center
}

# Day-Date-Month
label {
    monitor =
    text = cmd[update:3600000] date +"%d %b %A"
    color = $primary
    shadow_passes = 3
    shadow_size = 1
    font_size = 13
    font_family = CaskaydiaCove Nerd Font
    position = 1%, -1%
    halign = left
    valign = top
}

# SPLASH QUOTE
label {
    monitor =
    text = cmd[update:60000] hyprctl splash
    color = $primary
    shadow_passes = 3
    shadow_size = 1
    font_size = 14
    font_family = CaskaydiaCove Nerd Font
    position = 0, 20
    halign = center
    valign = bottom
}

image {
    monitor =
    path = ~/.face
    size = 80
    rounding = -1
    border_size = 0
    shadow_passes = 3
    shadow_size = 3
    border_color = rgb(221, 221, 221)
    rotate = 0
    reload_time = 0
    position = 0, 10%
    halign = center
    valign = bottom
}
