bar "bar-0" {
    colors {
        statusline {{colors.on_secondary.default.hex}}
        background {{colors.secondary.default.hex}}
        #border background text
        focused_workspace {{colors.primary_container.default.hex}} {{colors.primary.default.hex}} {{colors.on_primary.default.hex}}
        inactive_workspace {{colors.tertiary_container.default.hex}} {{colors.tertiary.default.hex}} {{colors.on_tertiary.default.hex}}
        urgent_workspace {{colors.primary_container.default.hex}} {{colors.error.default.hex}} {{colors.on_error.default.hex}}
    }
}
